database:
  address: "192.168.114.128"
  port: "5432"
  host: "postgres"
  password: "123456"
  output_status: True

udp_port:
  port_to_listen: 12345

schema_provider_port: "8081"

nginx:
  user_config_path: "/usr/local/nginx/conf/usr_conf"
  install_path: "/usr/local/nginx/sbin/nginx"

server_port: "8080"
